services:
  godot-docker:
    build: .
    user: "${UID}:${GID}"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - SDL_AUDIODRIVER=alsa
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11 socket
      - /dev/dri:/dev/dri              # GPU access for rendering
      - ${HOME}/Projects:/projects
      - /run/user/${UID}/pulse:/tmp/pulse:ro  # Pulse socket
      - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie:ro
      - /dev/snd:/dev/snd
      - /etc/asound.conf:/etc/asound.conf:ro
      # - ~/.asoundrc:/root/.asoundrc:ro
      - ./asound.conf:/etc/asound.conf:ro
    devices:
      - /dev/dri                       # GPU rendering interface
      - /dev/snd
    network_mode: host                 # So DISPLAY works
    privileged: true                   # Needed for direct /dev/dri access
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN